version: '3.8'

services:
  chat-with-pdf:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=8000
      - CHROMA_PERSIST_DIRECTORY=/app/data/chroma
      - PDF_DIRECTORY=/app/papers
    volumes:
      - ./papers:/app/papers:ro  # Mount PDFs as read-only
      - ./data:/app/data  # Mount data directory for persistence
    command: >
      sh -c "
        python scripts/ingest_pdfs.py --clear-existing &&
        python -m uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  chroma_data:
    driver: local 